name: ExtDN M2 Integration Tests
on:
  workflow_call:
    inputs:
      module_name:
        description: "Module name"
        required: true
        type: string
      composer_name:
        description: "Composer name"
        required: true
        type: string
jobs:
  integration-tests-2-4-4-p8-7-4:
    name: Magento 2.4.4-p8 PHP 7.4 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.4-p8 (PHP 7.4)
        uses: extdn/github-actions-m2/magento-integration-tests/7.4@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.4-p8'
          composer_version: '2'
  # skip Magento 2.4.4-p8 PHP 8.1 Integration Tests, because psr/log version 2 will be used with PHP 8.1,
  # which uses union types, which leads to issues in the code generator in older Magento versions like 2.4.4
  # see https://github.com/magento/magento2/issues/35292
  integration-tests-2-4-4-p9-7-4:
    name: Magento 2.4.4-p9 PHP 7.4 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.4-p9 (PHP 7.4)
        uses: extdn/github-actions-m2/magento-integration-tests/7.4@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.4-p9'
          composer_version: '2'
  integration-tests-2-4-4-p9-8-1:
    name: Magento 2.4.4-p9 PHP 8.1 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.4-p9 (PHP 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.4-p9'
          composer_version: '2'
  # skip Magento 2.4.5-p7 PHP 7.4 Integration Tests, because integration testing framework does not work with PHP 7.4
  # see https://github.com/extdn/github-actions-m2/issues/73
  integration-tests-2-4-5-p7-8-1:
    name: Magento 2.4.5-p7 PHP 8.1 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.5-p7 (PHP 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.5-p7'
          composer_version: '2'
  # skip Magento 2.4.5-p8 PHP 7.4 Integration Tests, because integration testing framework does not work with PHP 7.4
  # see https://github.com/extdn/github-actions-m2/issues/73
  integration-tests-2-4-5-p8-8-1:
    name: Magento 2.4.5-p8 PHP 8.1 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.5-p8 (PHP 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.5-p8'
          composer_version: '2'
  integration-tests-2-4-6-p5-8-1:
    name: Magento 2.4.6-p5 PHP 8.1 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.6-p5 (PHP 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.6-p5'
          composer_version: '2'
  integration-tests-2-4-6-p5-8-2:
    name: Magento 2.4.6-p5 PHP 8.2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.6-p5 (PHP 8.2)
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.6-p5'
          composer_version: '2'
  integration-tests-2-4-6-p6-8-1:
    name: Magento 2.4.6-p6 PHP 8.1 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.6-p6 (PHP 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.6-p6'
          composer_version: '2'
  integration-tests-2-4-6-p6-8-2:
    name: Magento 2.4.6-p6 PHP 8.2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.6-p6 (PHP 8.2)
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.6-p6'
          composer_version: '2'
  integration-tests-2-4-7-8-1:
    name: Magento 2.4.7 PHP 8.1 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.7 (PHP 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.7'
          composer_version: '2'
  integration-tests-2-4-7-8-2:
    name: Magento 2.4.7 PHP 8.2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.7 (PHP 8.2)
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.7'
          composer_version: '2'
  integration-tests-2-4-7-8-3:
    name: Magento 2.4.7 PHP 8.3 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.7 (PHP 8.3)
        uses: extdn/github-actions-m2/magento-integration-tests/8.3@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.7'
          composer_version: '2'
  integration-tests-2-4-7-p1-8-1:
    name: Magento 2.4.7-p1 PHP 8.1 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.7-p1 (PHP 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.7-p1'
          composer_version: '2'
  integration-tests-2-4-7-p1-8-2:
    name: Magento 2.4.7-p1 PHP 8.2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.7-p1 (PHP 8.2)
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.7-p1'
          composer_version: '2'
  integration-tests-2-4-7-p1-8-3:
    name: Magento 2.4.7-p1 PHP 8.3 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: M2 Integration Tests with Magento 2 Version 2.4.7-p1 (PHP 8.3)
        uses: extdn/github-actions-m2/magento-integration-tests/8.3@master
        with:
          module_name: ${{ inputs.module_name }}
          composer_name: ${{ inputs.composer_name }}
          magento_version: '2.4.7-p1'
          composer_version: '2'