name: ExtDN M2 PHPStan
on:
  workflow_call:
    inputs:
      composer_name:
        description: "Composer name"
        required: true
        type: string
      magento_pre_install_script:
        description: "Magento pre-install script"
        required: true
        type: string

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.3@master
        with:
          composer_name: ${{ inputs.composer_name }}
          magento_pre_install_script: ${{ inputs.magento_pre_install_script }}
