name: ExtDN M2 PHPStan
on: [workflow_call]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.2@master
        with:
          composer_name: customgento/module-cookiebot-m2
